name: Build Theos Project

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        uses: beerpiss/theos-action@v1
        with:
          theos-sdks: 'https://github.com/theos/sdks'

      - name: WeChatHook
        run: |
          export THEOS_PACKAGE_SCHEME=rootless 
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tweak-Deb
          path: packages/*.deb
